server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    url: jdbc:mysql://192.168.1.99:3306/cat01?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 10
    password: "@Root1234"
mybatis:
  type-aliases-package: com.javasm.springcloud
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    #true表示向注册中心注册自己，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      注册地址
#      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001
    #访问路径显示 IP 地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位秒（默认30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待的时间上限，单位秒（默认90秒），超时剔除服务
    lease-expiration-duration-in-seconds: 2
