server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
#  instance:
#    instance-id: payment8002
#    prefer-ip-address: true
  client:
    #true表示向注册中心注册自己，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      注册地址
      defaultZone: http://eureka7001.com:7001/eureka
