server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名称进行路由(默认false)


# com.javasm.springcloud.handler.PaymentController 中配置了两个路由
# http://127.0.0.1:9527/payment/get/1  访问到 8001
# 通过 URI 路由 和 predicates 断言判断有么有对应的访问地址，不暴露真实接口
      routes:
      # 路由 1

        - id: payment_route           # 路由的id,没有规定规则但要求唯一,建议配合服务名（随便配）
          uri: lb://CLOUD-PAYMENT-SERVICE  # 动态从 注册中心获取集群的服务地址，取代了 ribbon
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    # 断言，路径相匹配的进行路由，看 uri 下有没有 这样一个路径
                                      # ** 代表后面可能传的参数
            - After=2021-08-22T00:55:39.558+08:00[Asia/Shanghai]
                                      # 在这个时间后这个路由生效
            # - Cookie=username,zzyy    # 带Cookie，并且key为username，value为zzyy

      #路由 2
        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE
#          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**     # 断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/